scrape_configs:
  - job_name: postgres_exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]
  - job_name: 'db_metrics'
    static_configs:
      - targets: ['backend-imitation:8000']
      