#! /bin/bash

# psql -h $HOST -p $PORT -U $POSTGRES_USER -W $POSTGRES_PASSWORD -d $POSTGRES_DB -c "CREATE ROLE IF NOT EXISTS $CREATOR_NAME WITH LOGIN CREATEDB PASSWORD '$CREATOR_PASSWORD'"
# psql -h $HOST -p $PORT -U $CREATOR_NAME  -d $POSTGRES_DB -c "CREATE DATABASE IF NOT EXISTS $MY_DB OWNER $CREATOR_NAME"

# psql -tXA -h $HOST -U $POSTGRES_USER -d $POSTGRES_DB -p $PORT -c

role_name="$CREATOR_NAME"
if [[ $(psql -tXA --dbname="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOST:$PORT/$POSTGRES_DB" -c "SELECT 1 FROM pg_roles WHERE rolname='$role_name';") -ne "1" ]]
then
psql --dbname="postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@$HOST:$PORT/$POSTGRES_DB" -c "CREATE ROLE $CREATOR_NAME WITH LOGIN CREATEDB PASSWORD '$CREATOR_PASSWORD'"
fi

if [[ $(psql -tXA --dbname="postgresql://$CREATOR_NAME:$CREATOR_PASSWORD@$HOST:$PORT/$POSTGRES_DB" -c "SELECT 1 FROM pg_database WHERE datname='$MY_DB'") -ne "1" ]]
then
psql --dbname="postgresql://$CREATOR_NAME:$CREATOR_PASSWORD@$HOST:$PORT/$POSTGRES_DB" -c "CREATE DATABASE $MY_DB OWNER $CREATOR_NAME"
fi
